name = "MPIMagneticFields"
uuid = "f6dda52a-86e9-4b50-afb7-f39836a99446"
authors = ["Marija Boberg <m.boberg@uke.de> and contributors"]
version = "0.0.0"

[deps]

[compat]
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
